apiVersion: v1
kind: Service
metadata:
  name: nodejs-dns-resolver-service
spec:
  selector:
    app: nodejs-dns-resolver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
